/*CREATE TABLE [dbo].[PATIENT_BAK](
	--[id] [int] IDENTITY(1,1) NOT NULL,
	[PATIENT] [nvarchar](255) NULL,
	[CNAME] [nvarchar](255) NULL,
	[SEQ] [float] NULL,
	[SEX] [nvarchar](255) NULL,
	[BIRTH] [date] NULL,
	[AGE] [float] NULL,
	[HKID] [nvarchar](255) NULL,
	[UPDATE_BY] [nvarchar](255) NULL,
	[UPDATE_AT] [datetime] NULL,
	[UPDATE_CTR] [nvarchar](255) NULL,
	[UPDATED] [nvarchar](255) NULL,
) ON [PRIMARY]

GO


INSERT INTO [dbo].[PATIENT_BAK] ([PATIENT],[CNAME],[SEQ],[SEX],[BIRTH],[AGE],[HKID],[UPDATE_BY],[UPDATE_AT],[UPDATE_CTR],[UPDATED])
SELECT [PATIENT],[CNAME],[SEQ],[SEX],[BIRTH],[AGE],[HKID],[UPDATE_BY],[UPDATE_AT],[UPDATE_CTR],[UPDATED] FROM PATIENT

GO

TRUNCATE TABLE PATIENT

GO*/

ALTER TABLE PATIENT ADD [id] [int] IDENTITY(1,1) NOT NULL

GO

ALTER TABLE PATIENT ADD CONSTRAINT [PK_PATIENT] primary key (ID)

GO

/*INSERT INTO [dbo].[PATIENT] ([PATIENT],[CNAME],[SEQ],[SEX],[BIRTH],[AGE],[HKID],[UPDATE_BY],[UPDATE_AT],[UPDATE_CTR],[UPDATED])
SELECT [PATIENT],[CNAME],[SEQ],[SEX],[BIRTH],[AGE],[HKID],[UPDATE_BY],[UPDATE_AT],[UPDATE_CTR],[UPDATED] FROM PATIENT_BAK

GO

DROP TABLE PATIENT_BAK

GO*/