//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace St.Teresa_LIS_2019.HistologyWebserviceDev {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="HistologyWebservice", ConfigurationName="HistologyWebserviceDev.HistologyWebserviceSoap")]
    public interface HistologyWebserviceSoap {
        
        // CODEGEN: 命名空间 HistologyWebservice 的元素名称 psUserName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="HistologyWebservice/updateResult", ReplyAction="*")]
        St.Teresa_LIS_2019.HistologyWebserviceDev.updateResultResponse updateResult(St.Teresa_LIS_2019.HistologyWebserviceDev.updateResultRequest request);
        
        // CODEGEN: 命名空间 HistologyWebservice 的元素名称 psUserName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="HistologyWebservice/updateResultEHR", ReplyAction="*")]
        St.Teresa_LIS_2019.HistologyWebserviceDev.updateResultEHRResponse updateResultEHR(St.Teresa_LIS_2019.HistologyWebserviceDev.updateResultEHRRequest request);
        
        // CODEGEN: 命名空间 HistologyWebservice 的元素名称 psUserName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="HistologyWebservice/getPatient", ReplyAction="*")]
        St.Teresa_LIS_2019.HistologyWebserviceDev.getPatientResponse getPatient(St.Teresa_LIS_2019.HistologyWebserviceDev.getPatientRequest request);
        
        // CODEGEN: 命名空间 HistologyWebservice 的元素名称 psUserName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="HistologyWebservice/getDoctor", ReplyAction="*")]
        St.Teresa_LIS_2019.HistologyWebserviceDev.getDoctorResponse getDoctor(St.Teresa_LIS_2019.HistologyWebserviceDev.getDoctorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateResult", Namespace="HistologyWebservice", Order=0)]
        public St.Teresa_LIS_2019.HistologyWebserviceDev.updateResultRequestBody Body;
        
        public updateResultRequest() {
        }
        
        public updateResultRequest(St.Teresa_LIS_2019.HistologyWebserviceDev.updateResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="HistologyWebservice")]
    public partial class updateResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string psUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string psPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string psXMLDatagram;
        
        public updateResultRequestBody() {
        }
        
        public updateResultRequestBody(string psUserName, string psPassword, string psXMLDatagram) {
            this.psUserName = psUserName;
            this.psPassword = psPassword;
            this.psXMLDatagram = psXMLDatagram;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateResultResponse", Namespace="HistologyWebservice", Order=0)]
        public St.Teresa_LIS_2019.HistologyWebserviceDev.updateResultResponseBody Body;
        
        public updateResultResponse() {
        }
        
        public updateResultResponse(St.Teresa_LIS_2019.HistologyWebserviceDev.updateResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="HistologyWebservice")]
    public partial class updateResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string updateResultResult;
        
        public updateResultResponseBody() {
        }
        
        public updateResultResponseBody(string updateResultResult) {
            this.updateResultResult = updateResultResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateResultEHRRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateResultEHR", Namespace="HistologyWebservice", Order=0)]
        public St.Teresa_LIS_2019.HistologyWebserviceDev.updateResultEHRRequestBody Body;
        
        public updateResultEHRRequest() {
        }
        
        public updateResultEHRRequest(St.Teresa_LIS_2019.HistologyWebserviceDev.updateResultEHRRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="HistologyWebservice")]
    public partial class updateResultEHRRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string psUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string psPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string psXMLDatagram;
        
        public updateResultEHRRequestBody() {
        }
        
        public updateResultEHRRequestBody(string psUserName, string psPassword, string psXMLDatagram) {
            this.psUserName = psUserName;
            this.psPassword = psPassword;
            this.psXMLDatagram = psXMLDatagram;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateResultEHRResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateResultEHRResponse", Namespace="HistologyWebservice", Order=0)]
        public St.Teresa_LIS_2019.HistologyWebserviceDev.updateResultEHRResponseBody Body;
        
        public updateResultEHRResponse() {
        }
        
        public updateResultEHRResponse(St.Teresa_LIS_2019.HistologyWebserviceDev.updateResultEHRResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="HistologyWebservice")]
    public partial class updateResultEHRResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string updateResultEHRResult;
        
        public updateResultEHRResponseBody() {
        }
        
        public updateResultEHRResponseBody(string updateResultEHRResult) {
            this.updateResultEHRResult = updateResultEHRResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPatientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPatient", Namespace="HistologyWebservice", Order=0)]
        public St.Teresa_LIS_2019.HistologyWebserviceDev.getPatientRequestBody Body;
        
        public getPatientRequest() {
        }
        
        public getPatientRequest(St.Teresa_LIS_2019.HistologyWebserviceDev.getPatientRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="HistologyWebservice")]
    public partial class getPatientRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string psUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string psPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string psVisitNo;
        
        public getPatientRequestBody() {
        }
        
        public getPatientRequestBody(string psUserName, string psPassword, string psVisitNo) {
            this.psUserName = psUserName;
            this.psPassword = psPassword;
            this.psVisitNo = psVisitNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPatientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPatientResponse", Namespace="HistologyWebservice", Order=0)]
        public St.Teresa_LIS_2019.HistologyWebserviceDev.getPatientResponseBody Body;
        
        public getPatientResponse() {
        }
        
        public getPatientResponse(St.Teresa_LIS_2019.HistologyWebserviceDev.getPatientResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="HistologyWebservice")]
    public partial class getPatientResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getPatientResult;
        
        public getPatientResponseBody() {
        }
        
        public getPatientResponseBody(string getPatientResult) {
            this.getPatientResult = getPatientResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDoctorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDoctor", Namespace="HistologyWebservice", Order=0)]
        public St.Teresa_LIS_2019.HistologyWebserviceDev.getDoctorRequestBody Body;
        
        public getDoctorRequest() {
        }
        
        public getDoctorRequest(St.Teresa_LIS_2019.HistologyWebserviceDev.getDoctorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="HistologyWebservice")]
    public partial class getDoctorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string psUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string psPassword;
        
        public getDoctorRequestBody() {
        }
        
        public getDoctorRequestBody(string psUserName, string psPassword) {
            this.psUserName = psUserName;
            this.psPassword = psPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDoctorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDoctorResponse", Namespace="HistologyWebservice", Order=0)]
        public St.Teresa_LIS_2019.HistologyWebserviceDev.getDoctorResponseBody Body;
        
        public getDoctorResponse() {
        }
        
        public getDoctorResponse(St.Teresa_LIS_2019.HistologyWebserviceDev.getDoctorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="HistologyWebservice")]
    public partial class getDoctorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getDoctorResult;
        
        public getDoctorResponseBody() {
        }
        
        public getDoctorResponseBody(string getDoctorResult) {
            this.getDoctorResult = getDoctorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HistologyWebserviceSoapChannel : St.Teresa_LIS_2019.HistologyWebserviceDev.HistologyWebserviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HistologyWebserviceSoapClient : System.ServiceModel.ClientBase<St.Teresa_LIS_2019.HistologyWebserviceDev.HistologyWebserviceSoap>, St.Teresa_LIS_2019.HistologyWebserviceDev.HistologyWebserviceSoap {
        
        public HistologyWebserviceSoapClient() {
        }
        
        public HistologyWebserviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HistologyWebserviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HistologyWebserviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HistologyWebserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        St.Teresa_LIS_2019.HistologyWebserviceDev.updateResultResponse St.Teresa_LIS_2019.HistologyWebserviceDev.HistologyWebserviceSoap.updateResult(St.Teresa_LIS_2019.HistologyWebserviceDev.updateResultRequest request) {
            return base.Channel.updateResult(request);
        }
        
        public string updateResult(string psUserName, string psPassword, string psXMLDatagram) {
            St.Teresa_LIS_2019.HistologyWebserviceDev.updateResultRequest inValue = new St.Teresa_LIS_2019.HistologyWebserviceDev.updateResultRequest();
            inValue.Body = new St.Teresa_LIS_2019.HistologyWebserviceDev.updateResultRequestBody();
            inValue.Body.psUserName = psUserName;
            inValue.Body.psPassword = psPassword;
            inValue.Body.psXMLDatagram = psXMLDatagram;
            St.Teresa_LIS_2019.HistologyWebserviceDev.updateResultResponse retVal = ((St.Teresa_LIS_2019.HistologyWebserviceDev.HistologyWebserviceSoap)(this)).updateResult(inValue);
            return retVal.Body.updateResultResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        St.Teresa_LIS_2019.HistologyWebserviceDev.updateResultEHRResponse St.Teresa_LIS_2019.HistologyWebserviceDev.HistologyWebserviceSoap.updateResultEHR(St.Teresa_LIS_2019.HistologyWebserviceDev.updateResultEHRRequest request) {
            return base.Channel.updateResultEHR(request);
        }
        
        public string updateResultEHR(string psUserName, string psPassword, string psXMLDatagram) {
            St.Teresa_LIS_2019.HistologyWebserviceDev.updateResultEHRRequest inValue = new St.Teresa_LIS_2019.HistologyWebserviceDev.updateResultEHRRequest();
            inValue.Body = new St.Teresa_LIS_2019.HistologyWebserviceDev.updateResultEHRRequestBody();
            inValue.Body.psUserName = psUserName;
            inValue.Body.psPassword = psPassword;
            inValue.Body.psXMLDatagram = psXMLDatagram;
            St.Teresa_LIS_2019.HistologyWebserviceDev.updateResultEHRResponse retVal = ((St.Teresa_LIS_2019.HistologyWebserviceDev.HistologyWebserviceSoap)(this)).updateResultEHR(inValue);
            return retVal.Body.updateResultEHRResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        St.Teresa_LIS_2019.HistologyWebserviceDev.getPatientResponse St.Teresa_LIS_2019.HistologyWebserviceDev.HistologyWebserviceSoap.getPatient(St.Teresa_LIS_2019.HistologyWebserviceDev.getPatientRequest request) {
            return base.Channel.getPatient(request);
        }
        
        public string getPatient(string psUserName, string psPassword, string psVisitNo) {
            St.Teresa_LIS_2019.HistologyWebserviceDev.getPatientRequest inValue = new St.Teresa_LIS_2019.HistologyWebserviceDev.getPatientRequest();
            inValue.Body = new St.Teresa_LIS_2019.HistologyWebserviceDev.getPatientRequestBody();
            inValue.Body.psUserName = psUserName;
            inValue.Body.psPassword = psPassword;
            inValue.Body.psVisitNo = psVisitNo;
            St.Teresa_LIS_2019.HistologyWebserviceDev.getPatientResponse retVal = ((St.Teresa_LIS_2019.HistologyWebserviceDev.HistologyWebserviceSoap)(this)).getPatient(inValue);
            return retVal.Body.getPatientResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        St.Teresa_LIS_2019.HistologyWebserviceDev.getDoctorResponse St.Teresa_LIS_2019.HistologyWebserviceDev.HistologyWebserviceSoap.getDoctor(St.Teresa_LIS_2019.HistologyWebserviceDev.getDoctorRequest request) {
            return base.Channel.getDoctor(request);
        }
        
        public string getDoctor(string psUserName, string psPassword) {
            St.Teresa_LIS_2019.HistologyWebserviceDev.getDoctorRequest inValue = new St.Teresa_LIS_2019.HistologyWebserviceDev.getDoctorRequest();
            inValue.Body = new St.Teresa_LIS_2019.HistologyWebserviceDev.getDoctorRequestBody();
            inValue.Body.psUserName = psUserName;
            inValue.Body.psPassword = psPassword;
            St.Teresa_LIS_2019.HistologyWebserviceDev.getDoctorResponse retVal = ((St.Teresa_LIS_2019.HistologyWebserviceDev.HistologyWebserviceSoap)(this)).getDoctor(inValue);
            return retVal.Body.getDoctorResult;
        }
    }
}
